INSERT INTO question (question_text, answer, author) VALUES
    ('Что такое Spring Boot AutoConfiguration?', 'Механизм автоматической настройки компонентов приложения на основе зависимостей и условий в classpath.', 'Wersatil'),
    ('Как работает @SpringBootApplication с AutoConfiguration?', 'Аннотация включает @EnableAutoConfiguration, которая запускает автоматическую конфигурацию Spring Boot.', 'Wersatil'),
    ('Можно ли отключить AutoConfiguration?', 'Да, через @EnableAutoConfiguration(exclude = {ClassName.class}) или в application.properties/yml.', 'Wersatil'),
    ('Что такое application.yml?', 'Файл конфигурации Spring Boot в формате YAML для задания настроек приложения.', 'Wersatil'),
    ('Чем application.yml отличается от application.properties?', 'YAML поддерживает вложенные структуры и более читаемый формат, properties — простой key=value.', 'Wersatil'),
    ('Пример настройки server.port в application.yml?', 'server:\n  port: 8081', 'Wersatil'),
    ('Что такое Spring Profiles?', 'Механизм для разделения конфигурации на разные среды (dev, test, prod).', 'Wersatil'),
    ('Как активировать профиль Spring?', 'Через spring.profiles.active в application.yml или через переменные окружения.', 'Wersatil'),
    ('Можно ли иметь несколько профилей активными одновременно?', 'Да, через запятую: spring.profiles.active=dev,debug.', 'Wersatil'),
    ('Что такое @Profile?', 'Аннотация для бина или конфигурации, которая создается только для указанного профиля.', 'Wersatil'),
    ('Пример использования @Profile?', '@Bean\n@Profile("dev")\npublic DataSource devDataSource() { ... }', 'Wersatil'),
    ('Что такое Spring Boot Actuator?', 'Набор инструментов для мониторинга и управления Spring Boot приложением.', 'Wersatil'),
    ('Примеры эндпоинтов Actuator?', '/actuator/health, /actuator/metrics, /actuator/env, /actuator/info', 'Wersatil'),
    ('Как включить Actuator в проекте?', 'Добавить зависимость spring-boot-starter-actuator в build.gradle/pom.xml.', 'Wersatil'),
    ('Можно ли настроить доступ к Actuator эндпоинтам?', 'Да, через management.endpoints.web.exposure.include/exclude и настройки безопасности.', 'Wersatil'),
    ('Что такое /actuator/health?', 'Эндпоинт для проверки состояния приложения, обычно возвращает UP или DOWN.', 'Wersatil'),
    ('Что такое /actuator/metrics?', 'Эндпоинт, который возвращает метрики приложения, такие как память, загрузка CPU, http запросы.', 'Wersatil'),
    ('Что такое /actuator/env?', 'Эндпоинт, который показывает текущие переменные окружения и настройки приложения.', 'Wersatil'),
    ('Что такое Embedded server в Spring Boot?', 'Встроенный сервер (Tomcat, Jetty или Undertow), который позволяет запускать приложение без внешнего контейнера.', 'Wersatil'),
    ('Пример включения Tomcat в Spring Boot?', 'По умолчанию spring-boot-starter-web подключает встроенный Tomcat.', 'Wersatil'),
    ('Можно ли изменить порт Embedded server?', 'Да, через server.port в application.yml или properties.', 'Wersatil'),
    ('Можно ли сменить тип Embedded server?', 'Да, заменив зависимость spring-boot-starter-web на Jetty или Undertow.', 'Wersatil'),
    ('Что такое server.servlet.context-path?', 'Настройка контекста приложения, например /api.', 'Wersatil'),
    ('Что такое actuator endpoint exposure?', 'Указывает, какие эндпоинты доступны через web или JMX.', 'Wersatil'),
    ('Как защитить Actuator endpoints?', 'Через Spring Security, задав права доступа к /actuator/*.', 'Wersatil'),
    ('Можно ли добавить свои custom endpoints в Actuator?', 'Да, через @Endpoint и @ReadOperation/@WriteOperation/@DeleteOperation.', 'Wersatil'),
    ('Что такое management.server.port?', 'Это настройка Spring Boot, которая определяет, на каком порту будут доступны management-эндпоинты (Actuator). Проще: на каком порту слушают actuator. Management endpoints – это эндпоинты для мониторинга и управления приложением, которые предоставляет Spring Boot Actuator: health, metrics, info, prometheus и т.д.', 'Wersatil'),
    ('Что такое spring.main.banner-mode?', 'Настройка отображения баннера при старте приложения (OFF, CONSOLE, LOG).', 'Wersatil'),
    ('Как задать настройки по профилю в application.yml?', 'Использовать блоки с ключом spring.profiles: \n---\nspring:\n  profiles: dev\n  server.port: 8081', 'Wersatil'),
    ('Можно ли подключать разные application.yml для разных профилей?', 'Да, можно создать application-dev.yml, application-prod.yml и активировать профиль.', 'Wersatil'),
    ('Что такое conditional auto-configuration?', 'Автоматическая конфигурация, которая выполняется только если присутствуют определенные классы или бины.', 'Wersatil'),
    ('Пример conditional configuration?', '@ConditionalOnClass(DataSource.class) — конфигурация активна только если есть DataSource.', 'Wersatil'),
    ('Что делает spring-boot-starter?', 'Сборка зависимостей и конфигураций для быстрого старта приложения с нужным стеком.', 'Wersatil'),
    ('Примеры starter зависимостей?', 'spring-boot-starter-web, spring-boot-starter-data-jpa, spring-boot-starter-security.', 'Wersatil'),
    ('Что такое @EnableAutoConfiguration?', 'Аннотация, включающая механизм автоматической конфигурации Spring Boot.', 'Wersatil'),
    ('Можно ли переопределить AutoConfiguration бины?', 'Да, создав свой бин с таким же именем или типом, он заменит автоматически созданный.', 'Wersatil'),
    ('Что делает management.endpoints.web.exposure.include?', 'Указывает, какие Actuator эндпоинты будут доступны по web (например "*", "health", "info").', 'Wersatil'),
    ('Что делает management.endpoints.web.exposure.exclude?', 'Исключает определенные Actuator эндпоинты из web доступа.', 'Wersatil'),
    ('Что такое spring-boot-devtools?', 'Модуль для ускоренной разработки: автоматический рестарт, live reload, отключение кэширования.', 'Wersatil'),
    ('Что такое spring.config.import?', 'Механизм импорта дополнительных конфигурационных файлов в Spring Boot 2.4+.','Wersatil'),
    ('Что такое property overriding?', 'Переопределение свойств: свойства из профиля или командной строки имеют приоритет над application.yml.', 'Wersatil'),
    ('Можно ли запускать несколько приложений с разными профилями?', 'Да, через разные spring.profiles.active и порты Embedded server.', 'Wersatil'),
    ('Что такое actuator /info endpoint?', 'Эндпоинт для отображения информации о приложении, версии, сборке, свойствах.', 'Wersatil'),
    ('Что такое custom health indicator?', 'Пользовательский компонент, который добавляет проверку здоровья для Actuator /health.', 'Wersatil'),
    ('Как включить HTTP trace в Actuator?', 'management.endpoint.httptrace.enabled=true, добавляется endpoint /actuator/httptrace', 'Wersatil'),
    ('Что такое endpoint exposure через JMX?', 'Позволяет управлять Actuator эндпоинтами через JMX консоль.', 'Wersatil'),
    ('Что делает spring.main.allow-bean-definition-overriding?', 'Разрешает переопределение существующих бинов приложения.', 'Wersatil'),
    ('Что такое embedded servlet container factory?', 'Интерфейс для создания встроенных серверов (Tomcat, Jetty, Undertow) в Spring Boot.', 'Wersatil');