INSERT INTO question (question_text, answer, author) VALUES
    ('Что такое IoC (Inversion of Control)?', 'IoC — это принцип, при котором управление созданием и связыванием объектов передается контейнеру, а не самим объектам.', 'Wersatil'),
    ('Что такое DI (Dependency Injection)?', 'DI — это способ реализации IoC, при котором зависимости объекта внедряются контейнером.', 'Wersatil'),
    ('Какие типы DI существуют?', 'Constructor Injection, Setter Injection, Field Injection.', 'Wersatil'),
    ('Что такое @Component в Spring?', 'Аннотация для регистрации класса как Spring Bean, доступного для DI.', 'Wersatil'),
    ('Что такое @Service?', 'Специализация @Component для сервисного слоя, обозначает бизнес-логику.', 'Wersatil'),
    ('Что такое @Repository?', 'Специализация @Component для слоя доступа к данным, также обрабатывает DataAccessException.', 'Wersatil'),
    ('Чем @Component отличается от @Service и @Repository?', '@Service и @Repository — семантические аннотации для разных слоев, все являются @Component.', 'Wersatil'),
    ('Что делает @Autowired?', 'Внедряет зависимость в поле, конструктор или сеттер бина.', 'Wersatil'),
    ('Что такое constructor injection?', 'Внедрение зависимостей через конструктор класса.', 'Wersatil'),
    ('Почему constructor injection предпочтительнее field injection?', 'Обеспечивает immutable поля, удобнее для тестирования и гарантирует, что зависимость не null.', 'Wersatil'),
    ('Можно ли использовать @Autowired на поле?', 'Да, но это считается менее предпочтительным способом.', 'Wersatil'),
    ('Что такое Bean lifecycle в Spring?', 'Жизненный цикл бина — от создания, инициализации, работы до уничтожения.', 'Wersatil'),
    ('Какие основные этапы Bean lifecycle?', 'Создание -> Внедрение зависимостей -> Инициализация -> Использование -> Уничтожение.', 'Wersatil'),
    ('Как задать init-method?', 'Через атрибут initMethod в @Bean или реализацию интерфейса InitializingBean.', 'Wersatil'),
    ('Как задать destroy-method?', 'Через атрибут destroyMethod в @Bean или реализацию DisposableBean.', 'Wersatil'),
    ('Что такое @PostConstruct?', 'Аннотация для метода, который выполняется после внедрения зависимостей.', 'Wersatil'),
    ('Что такое @PreDestroy?', 'Аннотация для метода, который выполняется перед уничтожением бина.', 'Wersatil'),
    ('Что делает @Configuration?', 'Аннотация для класса, который содержит методы @Bean для явного создания бинов.', 'Wersatil'),
    ('Чем @Configuration отличается от @Component?', '@Configuration используется для конфигурационных классов с @Bean, @Component — для автоматической регистрации.', 'Wersatil'),
    ('Можно ли использовать @Bean без @Configuration?', 'Да, но в этом случае бин не является проксируемым, singleton может не работать как ожидается.', 'Wersatil'),
    ('Что такое singleton scope?', 'Singleton — один экземпляр бина на весь Spring контейнер (по умолчанию).', 'Wersatil'),
    ('Что такое prototype scope?', 'Prototype — каждый запрос на бин создает новый экземпляр.', 'Wersatil'),
    ('Как изменить scope бина?', 'С помощью аннотации @Scope("prototype") или @Scope("singleton").', 'Wersatil'),
    ('Какие есть другие scope в Spring?', 'request, session, application, websocket (для web-приложений).', 'Wersatil'),
    ('Что происходит при создании singleton бина?', 'Бин создается один раз при запуске контекста и используется во всем приложении.', 'Wersatil'),
    ('Что происходит при создании prototype бина?', 'Бин создается заново каждый раз, когда контейнер запрашивает его.', 'Wersatil'),
    ('Можно ли внедрять prototype бин в singleton?', 'Да, но нужно использовать ObjectProvider, @Lookup или Provider, чтобы каждый раз получать новый экземпляр.', 'Wersatil'),
    ('Что такое @Lazy?', 'Отложенная инициализация бина — бин создается только при первом обращении.', 'Wersatil'),
    ('Что делает @Primary?', 'Указывает, что бин является предпочтительным при множественном выборе кандидатов для DI.', 'Wersatil'),
    ('Что делает @Qualifier?', 'Позволяет выбрать конкретный бин для внедрения, если есть несколько кандидатов.', 'Wersatil'),
    ('Что такое circular dependency?', 'Когда два или более бина зависят друг от друга напрямую или через цепочку.', 'Wersatil'),
    ('Как Spring решает circular dependency для singleton?', 'Через раннюю регистрацию бина в кэше и setter injection, constructor injection не работает напрямую.', 'Wersatil'),
    ('Что произойдет, если circular dependency через constructor injection?', 'Контекст выбросит BeanCurrentlyInCreationException.', 'Wersatil'),
    ('Что такое BeanFactory?', 'Базовый контейнер Spring, обеспечивает базовую функциональность DI.', 'Wersatil'),
    ('Что такое ApplicationContext?', 'Расширение BeanFactory с поддержкой событий, i18n и более мощных возможностей.', 'Wersatil'),
    ('Можно ли получить бин из контекста вручную?', 'Да, через context.getBean(Class) или context.getBean(String).', 'Wersatil'),
    ('Что такое autowiring by type?', 'Spring ищет бин по типу для внедрения зависимости.', 'Wersatil'),
    ('Что такое autowiring by name?', 'Spring ищет бин по имени поля для внедрения.', 'Wersatil'),
    ('Что такое @Scope("prototype") в комбинации с @Autowired?', 'По умолчанию внедряется один раз, нужно использовать Provider или ObjectFactory для нового экземпляра.', 'Wersatil'),
    ('Что такое @PostConstruct в prototype бин?', 'Метод вызывается после внедрения зависимостей для каждого нового экземпляра.', 'Wersatil'),
    ('Можно ли иметь несколько @Configuration классов?', 'Да, Spring объединяет все конфигурации в контексте.', 'Wersatil'),
    ('Что такое @ComponentScan?', 'Аннотация для указания пакетов, где Spring ищет бины с аннотациями @Component, @Service, @Repository.', 'Wersatil'),
    ('Можно ли комбинировать @Configuration и @Component?', 'Да, @Configuration является @Component, может быть автоматически обнаружен через ComponentScan.', 'Wersatil'),
    ('Как Spring управляет жизненным циклом prototype бина?', 'Контейнер создает бин и внедряет зависимости, но не управляет destroy.', 'Wersatil'),
    ('Что делает @DependsOn?', 'Указывает, что бин зависит от других бинов и должен быть инициализирован после них.', 'Wersatil'),
    ('Можно ли внедрять интерфейсы через @Autowired?', 'Да, Spring ищет бин, который реализует интерфейс.', 'Wersatil'),
    ('Что такое @Lazy + singleton?', 'Бин создается один раз, но только при первом обращении.', 'Wersatil'),
    ('Можно ли внедрять коллекцию бинов через @Autowired?', 'Да, Spring автоматически собирает все бины данного типа в List или Map.', 'Wersatil'),
    ('Что такое default scope в Spring?', 'Singleton — один экземпляр на весь контейнер.', 'Wersatil');