INSERT INTO question (question_text, answer, author) VALUES
    ('Что такое @Controller в Spring?', 'Аннотация для обозначения класса как Spring MVC контроллера, который возвращает view.', 'Wersatil'),
    ('Что такое @RestController?', 'Комбинация @Controller и @ResponseBody, контроллер возвращает данные (JSON/ XML) вместо view.', 'Wersatil'),
    ('Чем @Controller отличается от @RestController?', '@Controller возвращает view, @RestController возвращает данные напрямую в теле ответа.', 'Wersatil'),
    ('Что делает @RequestMapping?', 'Позволяет настроить URL-путь и методы HTTP для обработки запроса.', 'Wersatil'),
    ('Что делает @GetMapping?', 'Сокращение для @RequestMapping с методом GET.', 'Wersatil'),
    ('Что делает @PostMapping?', 'Сокращение для @RequestMapping с методом POST.', 'Wersatil'),
    ('Что делает @PutMapping?', 'Сокращение для @RequestMapping с методом PUT.', 'Wersatil'),
    ('Что делает @DeleteMapping?', 'Сокращение для @RequestMapping с методом DELETE.', 'Wersatil'),
    ('Чем отличается @RequestParam от @PathVariable?', '@RequestParam получает значения из query-параметров, @PathVariable — из пути URL.', 'Wersatil'),
    ('Пример использования @RequestParam?', '/users?age=25 — @RequestParam("age") int age', 'Wersatil'),
    ('Пример использования @PathVariable?', '/users/5 — @PathVariable("id") Long id', 'Wersatil'),
    ('Что такое HTTP GET?', 'Метод запроса для получения ресурсов без изменения состояния сервера.', 'Wersatil'),
    ('Что такое HTTP POST?', 'Метод запроса для создания нового ресурса на сервере.', 'Wersatil'),
    ('Что такое HTTP PUT?', 'Метод запроса для полного обновления ресурса.', 'Wersatil'),
    ('Что такое HTTP PATCH?', 'Метод запроса для частичного обновления ресурса.', 'Wersatil'),
    ('Что такое HTTP DELETE?', 'Метод запроса для удаления ресурса.', 'Wersatil'),
    ('Какой статус возвращает успешный GET?', '200 OK', 'Wersatil'),
    ('Какой статус возвращает успешный POST?', '201 Created', 'Wersatil'),
    ('Какой статус возвращает успешный DELETE?', '204 No Content', 'Wersatil'),
    ('Что означает статус 400?', 'Bad Request — некорректный запрос от клиента.', 'Wersatil'),
    ('Что означает статус 401?', 'Unauthorized — клиент не аутентифицирован.', 'Wersatil'),
    ('Что означает статус 403?', 'Forbidden — клиент не имеет прав доступа.', 'Wersatil'),
    ('Что означает статус 404?', 'Not Found — ресурс не найден на сервере.', 'Wersatil'),
    ('Что означает статус 500?', 'Internal Server Error — ошибка сервера.', 'Wersatil'),
    ('Что такое idempotent HTTP метод?', 'Метод, который можно вызывать несколько раз без изменения результата (например, GET, PUT, DELETE).', 'Wersatil'),
    ('Какие HTTP методы идемпотентные?', 'GET, PUT, DELETE, HEAD, OPTIONS.', 'Wersatil'),
    ('Какие HTTP методы не идемпотентные?', 'POST, PATCH.', 'Wersatil'),
    ('Что такое REST?', 'REST — архитектурный стиль для веб-сервисов, основанный на ресурсах и стандартных HTTP методах.', 'Wersatil'),
    ('Основные принципы REST?', '1) Клиент-сервер, 2) Stateless, 3) Cacheable, 4) Единый интерфейс, 5) Layered system, 6) Code on demand (опционально)', 'Wersatil'),
    ('Что означает stateless в REST?', 'Каждый запрос содержит всю необходимую информацию, сервер не хранит состояние клиента.', 'Wersatil'),
    ('Что означает cacheable в REST?', 'Ответы могут кэшироваться для повышения производительности.', 'Wersatil'),
    ('Что такое единый интерфейс в REST?', 'Использование стандартных HTTP методов и согласованного формата данных.', 'Wersatil'),
    ('Что такое resource в REST?', 'Любой объект, к которому можно получить доступ через уникальный URI.', 'Wersatil'),
    ('Как правильно организовать URL для коллекции ресурсов?', '/users — для списка пользователей, /users/5 — для конкретного пользователя.', 'Wersatil'),
    ('Что такое HATEOAS в REST?', 'Hypermedia as the Engine of Application State — клиент получает ссылки для перехода по ресурсам.', 'Wersatil'),
    ('Можно ли использовать @RequestParam для обязательного параметра?', 'Да, через required=true (по умолчанию true).', 'Wersatil'),
    ('Можно ли использовать @RequestParam с defaultValue?', 'Да, если параметр отсутствует, используется значение по умолчанию.', 'Wersatil'),
    ('Как вернуть JSON из @RestController?', 'Просто вернуть объект или коллекцию, Spring автоматически сериализует в JSON.', 'Wersatil'),
    ('Можно ли @Controller вернуть JSON?', 'Да, с использованием @ResponseBody или ResponseEntity.', 'Wersatil'),
    ('Что делает ResponseEntity?', 'Позволяет задать тело, статус и заголовки HTTP ответа.', 'Wersatil'),
    ('Можно ли использовать @PathVariable и @RequestParam одновременно?', 'Да, можно комбинировать оба типа параметров в одном методе.', 'Wersatil'),
    ('Что такое content negotiation?', 'Механизм выбора формата ответа (JSON, XML) в зависимости от запроса клиента.', 'Wersatil'),
    ('Как настроить content type ответа?', 'Через @RequestMapping(produces="application/json") или HTTP header Accept.', 'Wersatil'),
    ('Что такое query parameter?', 'Параметр, переданный в URL после ? (например, /users?age=25).', 'Wersatil'),
    ('Что такое path parameter?', 'Параметр, часть пути URL (например, /users/5).', 'Wersatil'),
    ('Как обработать разные HTTP методы для одного URL?', 'Через @RequestMapping(path="/users", method=GET/POST/PUT/DELETE).', 'Wersatil'),
    ('Что делает @ResponseStatus?', 'Позволяет задать HTTP статус, возвращаемый методом контроллера.', 'Wersatil'),
    ('Как обрабатывать исключения в REST?', 'Через @ExceptionHandler, @ControllerAdvice или ResponseEntityExceptionHandler.', 'Wersatil'),
    ('Можно ли комбинировать @Controller и @RestController в одном проекте?', 'Да, @Controller для view, @RestController для REST API.', 'Wersatil');
