INSERT INTO question (question_text, answer, author) VALUES
    ('Что такое IoC (Inversion of Control)?', 'IoC — это принцип, при котором управление созданием и связыванием объектов передается контейнеру, а не самим объектам.', 'Wersatil'),
    ('Что такое DI (Dependency Injection)?', 'DI — это способ реализации IoC, при котором зависимости объекта внедряются контейнером.', 'Wersatil'),
    ('Какие типы DI существуют?', 'Constructor Injection, Setter Injection, Field Injection.', 'Wersatil'),
    ('Что такое AOP-прокси?', 'Объект-обёртка, который Spring создаёт вместо реального бина, чтобы перехватывать вызовы его методов и применять сквозную функциональность (aspects)..', 'Wersatil'),
    ('На каком этапе создаётся AOP-прокси?', 'В postProcessAfterInitialization.', 'Wersatil'),
    ('Чем различаются @Component, @Service и @Repository?', '@Service не отличается от @Component, нужен для понимания логики. @Repository автоматически перехватывает исключения и превращает их в DataAccessException.', 'Wersatil'),
    ('Что делает @Autowired?', 'Внедряет зависимость в поле, конструктор или сеттер бина.', 'Wersatil'),
    ('Почему constructor injection предпочтительнее field injection?', 'Обеспечивает immutable поля, удобнее для тестирования и гарантирует, что зависимость не null.', 'Wersatil'),
    ('Можно ли использовать @Autowired на поле?', 'Да, но это считается менее предпочтительным способом.', 'Wersatil'),
    ('Что такое Bean lifecycle в Spring?', 'Жизненный цикл бина — от создания, инициализации, работы до уничтожения.', 'Wersatil'),
    ('Какие основные этапы Bean lifecycle?', 'Создание -> Внедрение зависимостей -> Инициализация -> Использование -> Уничтожение.', 'Wersatil'),
    ('Как задать init-method?', 'Через атрибут initMethod в @Bean или реализацию интерфейса InitializingBean.', 'Wersatil'),
    ('Как задать destroy-method?', 'Через атрибут destroyMethod в @Bean или реализацию DisposableBean.', 'Wersatil'),
    ('Что такое @PostConstruct?', 'Аннотация для метода, который выполняется ПОСЛЕ внедрения зависимостей.', 'Wersatil'),
    ('Что такое @PreDestroy?', 'Аннотация для метода, который выполняется перед уничтожением бина.', 'Wersatil'),
    ('Чем @Configuration отличается от @Component?', '@Configuration используется для конфигурационных классов с @Bean, @Component — для автоматической регистрации.', 'Wersatil'),
    ('Можно ли использовать @Bean без @Configuration?', 'Да, но в этом случае бин не является проксируемым, singleton может не работать как ожидается.', 'Wersatil'),
    ('В чем разница между singleton scope и prototype scope?', 'Singleton создает один экземпляр бина на все приложение, prototype создает новый бин при каждом вызове.', 'Wersatil'),
    ('Как изменить scope бина?', 'С помощью аннотации @Scope("prototype") или @Scope("singleton").', 'Wersatil'),
    ('Какие существуют scope в Spring?', 'Singleton, prototype, request, session, application, websocket (для web-приложений).', 'Wersatil'),
    ('Что нужно использовать, чтобы внедрить prototype бин в singleton?', 'ObjectProvider, @Lookup или Provider, чтобы каждый раз получать новый экземпляр.', 'Wersatil'),
    ('Что делает @Primary?', 'Указывает, что бин является предпочтительным при множественном выборе кандидатов для DI.', 'Wersatil'),
    ('Что делает @Qualifier?', 'Позволяет выбрать конкретный бин для внедрения, если есть несколько кандидатов.', 'Wersatil'),
    ('Что такое circular dependency в Spring?', 'Когда два или более бина зависят друг от друга напрямую или через цепочку.', 'Wersatil'),
    ('Как Spring решает circular dependency для singleton?', 'Через раннюю регистрацию бина в кэше и setter injection, constructor injection не работает напрямую.', 'Wersatil'),
    ('Что произойдет, если circular dependency возникает при constructor injection?', 'Контекст выбросит BeanCurrentlyInCreationException.', 'Wersatil'),
    ('Что такое BeanFactory?', 'Базовый контейнер Spring, обеспечивает базовую функциональность DI.', 'Wersatil'),
    ('Что такое ApplicationContext?', 'Расширение BeanFactory с поддержкой событий, i18n и более мощных возможностей.', 'Wersatil'),
    ('Как можно получить бин из контекста вручную?', 'Через вызов context.getBean(Class) или context.getBean(String).', 'Wersatil'),
    ('Чем отличается autowiring by type от autowiring by name?', 'В первом случае Spring ищет бин по типу, в другом по имени для внедрения зависимости.', 'Wersatil'),
    ('Что происходит при @PostConstruct в prototype бин?', 'Метод вызывается после внедрения зависимостей для каждого нового экземпляра.', 'Wersatil'),
    ('Что такое @ComponentScan и когда ее нужно использовать?', 'Аннотация для указания пакетов, где Spring ищет бины с аннотациями @Component, @Service, @Repository. Используем, если: бины лежат в разных корневых пакетах или нужно одни классы включить, а другие исключить.', 'Wersatil'),
    ('Можно ли комбинировать @Configuration и @Component?', 'Да, @Configuration является @Component, может быть автоматически обнаружен через ComponentScan.', 'Wersatil'),
    ('Какими этапами жизненного цикла бинов singleton и prototype управляет Spring?', 'Spring управляет prototype-бином только при создании. Дальше — нет. У Singleton управляет всем жизненным циклом.', 'Wersatil'),
    ('Что делает @DependsOn в Spring?', 'Указывает, что бин зависит от других бинов и должен быть инициализирован после них.', 'Wersatil'),
    ('Можно ли внедрять интерфейсы через @Autowired?', 'Да, Spring ищет бин, который реализует интерфейс.', 'Wersatil'),
    ('Каков принцип создания singleton-бинов при аннотации @Lazy в Spring?', 'Бин создается один раз, но только при первом обращении.', 'Wersatil'),
    ('Можно ли внедрять коллекцию бинов через @Autowired?', 'Да, Spring автоматически собирает все бины данного типа в List или Map.', 'Wersatil'),
    ('Каково значение default scope в Spring?', 'Singleton — один экземпляр на весь контейнер.', 'Wersatil');