INSERT INTO question (question_text, answer, author) VALUES
    ('Что такое аутентификация?', 'Процесс проверки личности пользователя (кто он есть).', 'Wersatil'),
    ('Что такое авторизация?', 'Процесс проверки прав пользователя на выполнение действий или доступ к ресурсам.', 'Wersatil'),
    ('Чем аутентификация отличается от авторизации?', 'Аутентификация — проверка личности, авторизация — проверка прав.', 'Wersatil'),
    ('Что такое JWT?', 'JSON Web Token — компактный токен для передачи данных о пользователе и правах между клиентом и сервером.', 'Wersatil'),
    ('Что содержит JWT?', 'Header, Payload (данные и claims), Signature.', 'Wersatil'),
    ('Что такое Header в JWT?', 'Информация о типе токена и используемом алгоритме подписи.', 'Wersatil'),
    ('Что содержит Payload в JWT?', 'Claims — информацию о пользователе, срок действия, роль и другие данные.', 'Wersatil'),
    ('Что такое Signature в JWT?', 'Подпись токена для проверки его целостности и аутентичности.', 'Wersatil'),
    ('Что такое SecurityFilterChain?', 'Цепочка фильтров Spring Security, которая обрабатывает запросы, аутентификацию и авторизацию.', 'Wersatil'),
    ('Как настроить SecurityFilterChain?', 'Через Bean SecurityFilterChain в конфигурации Spring Security.', 'Wersatil'),
    ('Что такое @PreAuthorize?', 'Аннотация для проверки прав пользователя перед выполнением метода на основе выражений SpEL.', 'Wersatil'),
    ('Что такое CSRF?', 'Cross-Site Request Forgery — атака, при которой злоумышленник заставляет пользователя выполнить нежелательное действие.', 'Wersatil'),
    ('Как Spring Security защищает от CSRF?', 'Включает CSRF токен, который должен отправляться с изменяющими состояние запросами (POST, PUT, DELETE).', 'Wersatil'),
    ('Когда CSRF можно отключить?', 'Для stateless REST API или при использовании JWT, где токен уже защищает запрос.', 'Wersatil'),
    ('Что такое CORS?', 'Cross-Origin Resource Sharing — механизм, который контролирует доступ к ресурсам из других доменов.', 'Wersatil'),
    ('Как включить CORS в Spring?', 'Через @CrossOrigin на контроллере или глобально через WebMvcConfigurer.', 'Wersatil'),
    ('Что такое OAuth2?', 'Протокол авторизации, который позволяет приложению получать доступ к ресурсам от имени пользователя без передачи пароля.', 'Wersatil'),
    ('Назовите основные роли в OAuth2?', 'Resource Owner, Client, Authorization Server, Resource Server.', 'Wersatil'),
    ('Что такое Access Token в OAuth2?', 'Токен, который клиент использует для доступа к защищенным ресурсам.', 'Wersatil'),
    ('Что такое Refresh Token?', 'Токен, который позволяет получить новый Access Token без повторной аутентификации пользователя.', 'Wersatil'),
    ('Опишите пример потока Authorization Code в OAuth2?', 'Клиент получает код авторизации, меняет его на Access Token через Authorization Server.', 'Wersatil'),
    ('Опишите пример потока Client Credentials в OAuth2?', 'Клиент получает Access Token напрямую от Authorization Server, без участия пользователя.', 'Wersatil'),
    ('Что такое Bearer Token?', 'Формат токена, который передается в заголовке Authorization: Bearer <token>.', 'Wersatil'),
    ('Как Spring Security работает с JWT?', 'Фильтр проверяет токен, извлекает пользователя и права, устанавливает Authentication в SecurityContext.', 'Wersatil'),
    ('Что такое AuthenticationManager?', 'Компонент, который отвечает за аутентификацию пользователя в Spring Security.', 'Wersatil'),
    ('Что такое UserDetails?', 'Интерфейс Spring Security, который описывает пользователя (логин, пароль, роли).', 'Wersatil'),
    ('Что такое UserDetailsService?', 'Интерфейс для загрузки пользователя по username для аутентификации.', 'Wersatil'),
    ('Что делает SecurityContextHolder?', 'Хранит текущий контекст безопасности с информацией об Authentication пользователя.', 'Wersatil'),
    ('Что такое stateless authentication?', 'Аутентификация без хранения состояния на сервере, например с JWT.', 'Wersatil'),
    ('Что такое stateful authentication?', 'Аутентификация с хранением сессии на сервере, например через HttpSession.', 'Wersatil'),
    ('Что такое principal в Spring Security?', 'Сущность, представляющая аутентифицированного пользователя.', 'Wersatil'),
    ('Что такое GrantedAuthority?', 'Интерфейс, представляющий права или роли пользователя.', 'Wersatil'),
    ('Чем roles отличается от authorities в Spring Security?', 'Role — абстрактная роль пользователя, authority — конкретное право, роль может содержать несколько authorities.', 'Wersatil'),
    ('Что такое JWT expiration?', 'Срок действия токена, после которого он недействителен.', 'Wersatil'),
    ('Как обновлять JWT после истечения срока?', 'Через Refresh Token, который выдаёт новый Access Token.', 'Wersatil'),
    ('Что такое CSRF token?', 'Секретный токен, который предотвращает подделку запросов между сайтами.', 'Wersatil'),
    ('Почему REST API часто не требует CSRF?', 'Потому что REST обычно stateless и использует токены (JWT), которые защищают от подделки запросов.', 'Wersatil'),
    ('Что такое CORS preflight request?', 'OPTIONS запрос, который браузер отправляет для проверки допустимости кросс-доменных запросов.', 'Wersatil'),
    ('Что такое OAuth2 scopes?', 'Набор прав доступа, которые клиент запрашивает у Authorization Server.', 'Wersatil'),
    ('Пример scope в OAuth2?', 'read, write, admin — указываются при запросе токена для ограничения доступа.', 'Wersatil'),
    ('Что такое OpenID Connect (OIDC)?', 'Протокол аутентификации поверх OAuth2, который возвращает информацию о пользователе.', 'Wersatil'),
    ('Что такое refresh flow в OAuth2?', 'Использование Refresh Token для получения нового Access Token без повторной аутентификации.', 'Wersatil'),
    ('Что такое stateless JWT filter?', 'Фильтр, который проверяет JWT на каждом запросе без использования сессии.', 'Wersatil'),
    ('Как защитить API от неавторизованных запросов?', 'Настроить SecurityFilterChain с авторизацией и проверкой JWT токена.', 'Wersatil'),
    ('Что такое AuthenticationEntryPoint?', 'Компонент Spring Security, который обрабатывает попытки доступа без аутентификации.', 'Wersatil'),
    ('Что такое AccessDeniedHandler?', 'Компонент Spring Security, который обрабатывает доступ запрещён (403) для аутентифицированного пользователя.', 'Wersatil');