INSERT INTO question (question_text, answer, author) VALUES
    ('Что такое propagation в транзакциях?', 'Поведение транзакции при вызове другого метода, который тоже транзакционный.', 'Wersatil'),
    ('По какому принципу работает режим Propagation.REQUIRED?', 'Если транзакция уже есть → использовать её. Если нет → создать новую.', 'Wersatil'),
    ('По какому принципу работает режим Propagation.REQUIRES_NEW?', 'Всегда создает новую транзакцию, при этом существующая приостанавливается.', 'Wersatil'),
    ('По какому принципу работает режим Propagation.NESTED?', 'Создает вложенную транзакцию с использованием savepoint, если есть существующая транзакция.', 'Wersatil'),
    ('По какому принципу работает режим propagation.NOT_SUPPORTED?', 'Приостанавливает текущую транзакцию, метод выполняется без нее.', 'Wersatil'),
    ('Что такое propagation.SUPPORTS?', 'Один из режимов транзакций в Spring, который определяет поведение метода относительно существующей транзакции. Если транзакция уже есть → использовать её. Если транзакции нет → выполнять метод без транзакции.', 'Wersatil'),
    ('Что делает Isolation?', 'Определяет уровень изоляции между параллельными транзакциями.', 'Wersatil'),
    ('Что такое rollback в Spring?', 'Откат транзакции при ошибке или исключении.', 'Wersatil'),
    ('Что является триггером для отката транзакции в Spring?', 'Исключение. По умолчанию только Unchecked exception или Error, но список исключений можно перенастраивать.', 'Wersatil'),
    ('Можно ли откатить транзакцию при checked исключении?', 'Да, если настроить через параметр rollbackFor в @Transactional.', 'Wersatil'),
    ('Что перенастраивает параметр noRollbackFor в @Transactional?', '@Transactional(noRollbackFor = SomeException.class) — исключение не вызывает откат.', 'Wersatil'),
    ('Чем отличается programmatic и declarative транзакции?', 'Programmatic — управление через TransactionTemplate или EntityManager, declarative — через @Transactional.', 'Wersatil'),
    ('Что такое TransactionManager в Spring?', 'Интерфейс, управляющий транзакциями, например, PlatformTransactionManager.', 'Wersatil'),
    ('Можно ли смешивать разные TransactionManager в проекте?', 'Да, но нужно явно указывать бин через @Transactional("transactionManagerName").', 'Wersatil'),
    ('Что такое savepoint в транзакции?', 'Точка, к которой можно откатиться без полного отката транзакции.', 'Wersatil'),
    ('Как Nested транзакции используют savepoint?', 'При Propagation.NESTED создается savepoint, rollback откатывает до него.', 'Wersatil'),
    ('Что такое rollback-only?', 'Флаг, устанавливаемый вручную для отката транзакции без выброса исключения.', 'Wersatil'),
    ('Что такое ChainedTransactionManager?', 'Менеджер транзакций для работы с несколькими ресурсами одновременно.', 'Wersatil'),
    ('Можно ли управлять временем ожидания транзакции?', 'Да, через параметр timeout в @Transactional.', 'Wersatil'),
    ('Что такое nested transaction rollback?', 'Откат только вложенной транзакции до savepoint без отката родителя.', 'Wersatil'),
    ('Что означает propagation MANDATORY?', 'Метод должен быть вызван внутри существующей транзакции, иначе выбрасывается исключение.', 'Wersatil'),
    ('Что означает propagation NEVER?', 'Метод не должен выполняться в транзакции, иначе выбрасывается исключение.', 'Wersatil'),
    ('Как @Transactional влияет на lazy загрузку?', '@Transactional не делает поле lazy сразу доступным, но обеспечивает открытую сессию Hibernate. Без транзакции lazy loading вызывает LazyInitializationException', 'Wersatil'),
    ('Можно ли комбинировать readOnly и propagation?', 'Да, например @Transactional(readOnly=true, propagation=REQUIRED).', 'Wersatil'),
    ('Что такое propagation?', 'Правило, которое определяет, как метод с транзакцией должен взаимодействовать с уже существующей транзакцией.', 'Wersatil'),
    ('Что предпочтительнее: декларативные транзакции или программные?', 'Декларативные. В них меньше кода, их легче поддерживать и интегрировать с AOP.', 'Wersatil'),
    ('Что происходит при исключении внутри nested транзакции?', 'Только вложенная транзакция откатывается до savepoint, родительская продолжается.', 'Wersatil'),
    ('Что делает rollbackForClassName?', 'Позволяет указать имя класса исключения для отката транзакции.', 'Wersatil'),
    ('Можно ли использовать @Transactional на интерфейсе?', 'Да, если используется JDK dynamic proxy, но лучше на классе.', 'Wersatil'),
    ('Можно ли комбинировать @Transactional и async?', 'Да, но нужно понимать, что @Async выполняется в другом потоке, транзакции не разделяются автоматически.', 'Wersatil'),
    ('Как проверить, находится ли транзакция в процессе?', 'С помощью вызова метода TransactionSynchronizationManager.isActualTransactionActive()', 'Wersatil'),
    ('Что такое global rollback?', 'Откат всей транзакции вместе со всеми nested и внутренними вызовами.', 'Wersatil'),
    ('Что такое local rollback?', 'Откат только части транзакции, например через savepoint в nested транзакции.', 'Wersatil');