INSERT INTO question (question_text, answer, author) VALUES
    ('Что такое Layered Architecture?', 'Архитектура приложения, разделяющая код на слои: Controller, Service, Repository.', 'Wersatil'),
    ('Зачем нужна слоистая архитектура?', 'Для разделения ответственности, улучшения тестируемости и поддержки кода.', 'Wersatil'),
    ('Что делает слой Controller?', 'Обрабатывает HTTP-запросы и отвечает клиенту.', 'Wersatil'),
    ('Что делает слой Service?', 'Содержит бизнес-логику приложения.', 'Wersatil'),
    ('Что делает слой Repository?', 'Отвечает за доступ к базе данных.', 'Wersatil'),
    ('Что такое DTO?', 'Data Transfer Object — объект для передачи данных между слоями без бизнес-логики.', 'Wersatil'),
    ('Зачем использовать DTO?', 'Чтобы отделить внутренние сущности от данных, которые отправляются клиенту или принимаются от него.', 'Wersatil'),
    ('Что такое MapStruct?', 'Фреймворк для автоматического маппинга между DTO и Entity.', 'Wersatil'),
    ('Пример использования MapStruct?', '@Mapper\npublic interface UserMapper { UserDTO toDto(User user); }', 'Wersatil'),
    ('Чем MapStruct лучше ручного маппинга?', 'Генерирует код на этапе компиляции, меньше ошибок и повышает производительность.', 'Wersatil'),
    ('Что делает @Mapping в MapStruct?', 'Позволяет настроить сопоставление полей с разными именами.', 'Wersatil'),
    ('Что такое @ControllerAdvice?', 'Аннотация для глобальной обработки исключений в Spring MVC.', 'Wersatil'),
    ('Что делает @ExceptionHandler?', 'Метод обрабатывает конкретный тип исключения и формирует ответ клиенту.', 'Wersatil'),
    ('Пример глобального ExceptionHandler?', '@ControllerAdvice\npublic class GlobalExceptionHandler { @ExceptionHandler(Exception.class) ... }', 'Wersatil'),
    ('Что такое ResponseEntity?', 'Объект для передачи HTTP-статуса, заголовков и тела ответа клиенту.', 'Wersatil'),
    ('Как вернуть кастомный error response?', 'Создать DTO для ошибки и вернуть через ResponseEntity с нужным статусом.', 'Wersatil'),
    ('Что такое Logging в Spring?', 'Запись информации о работе приложения для отладки, мониторинга и анализа.', 'Wersatil'),
    ('Популярные библиотеки для логирования?', 'SLF4J, Logback, Log4j2.', 'Wersatil'),
    ('Пример логирования через SLF4J?', 'private static final Logger log = LoggerFactory.getLogger(MyClass.class);\nlog.info("message");', 'Wersatil'),
    ('Какие уровни логирования бывают?', 'TRACE, DEBUG, INFO, WARN, ERROR.', 'Wersatil'),
    ('Что такое REST error handling?', 'Обработка ошибок в REST API с возвращением структурированного ответа клиенту.', 'Wersatil'),
    ('Пример REST error response?', '{ "timestamp": "2025-12-26T12:00:00", "status": 400, "error": "Bad Request", "message": "Invalid input" }', 'Wersatil'),
    ('Чем глобальный обработчик отличается от локального?', 'Глобальный через @ControllerAdvice обрабатывает все контроллеры, локальный через @ExceptionHandler — только внутри класса.', 'Wersatil'),
    ('Что такое ApiError DTO?', 'DTO для структурирования ошибок REST API, содержит статус, сообщение, timestamp и другие данные.', 'Wersatil'),
    ('Что такое BindingResult?', 'Объект для проверки ошибок валидации при использовании @Valid в контроллере.', 'Wersatil'),
    ('Пример обработки MethodArgumentNotValidException?', '@ExceptionHandler(MethodArgumentNotValidException.class) ... формируем список ошибок валидации', 'Wersatil'),
    ('Что такое GlobalExceptionHandler?', 'Класс с @ControllerAdvice, который централизованно обрабатывает все исключения приложения.', 'Wersatil'),
    ('Как вернуть разный HTTP статус для разных исключений?', 'Через @ExceptionHandler для каждого типа исключения и ResponseEntity с нужным статусом.', 'Wersatil'),
    ('Что такое Validation DTO?', 'DTO с аннотациями валидации (@NotNull, @Size, @Email) для проверки данных входящих запросов.', 'Wersatil'),
    ('Как использовать @Valid?', 'Проставить @Valid перед DTO в контроллере для активации валидации.', 'Wersatil'),
    ('Что делает @Slf4j?', 'Ломбок-аннотация, автоматически создает логгер для класса.', 'Wersatil'),
    ('Что такое nested exception handling?', 'Обработка исключений, которые вложены друг в друга (cause), например при PersistenceException.', 'Wersatil'),
    ('Как обрабатывать кастомные бизнес-исключения?', 'Создать свой класс исключения и обработчик в @ControllerAdvice.', 'Wersatil'),
    ('Что такое ErrorAttributes?', 'Интерфейс Spring Boot для формирования структуры ответа при ошибке.', 'Wersatil'),
    ('Что делает DefaultErrorAttributes?', 'Стандартная реализация Spring Boot для создания error response в /error.', 'Wersatil'),
    ('Как добавить кастомные поля в error response?', 'Создать свой класс, реализующий ErrorAttributes и переопределить getErrorAttributes().', 'Wersatil'),
    ('Что такое centralized logging?', 'Сбор логов с разных компонентов приложения в одном месте для анализа.', 'Wersatil'),
    ('Пример использования MDC в логировании?', 'Добавление контекста (например userId) в каждый лог: MDC.put("userId", id);', 'Wersatil'),
    ('Что такое structured logging?', 'Логирование в формате JSON или с ключами для удобного анализа в ELK или Grafana.', 'Wersatil'),
    ('Что такое logging pattern?', 'Формат записи лога, например: %d{HH:mm:ss} %-5level %logger{36} - %msg%n', 'Wersatil'),
    ('Что такое @Mapper(componentModel = "spring")?', 'Указывает MapStruct создавать бин Spring для внедрения через @Autowired.', 'Wersatil'),
    ('Чем MapStruct отличается от ModelMapper?', 'MapStruct генерирует код на этапе компиляции, ModelMapper делает маппинг во время выполнения.', 'Wersatil'),
    ('Как обрабатывать ValidationException глобально?', 'Создать @ExceptionHandler(ValidationException.class) в @ControllerAdvice и вернуть ResponseEntity с ошибкой.', 'Wersatil'),
    ('Что такое ResponseStatusException?', 'Класс для выброса исключения с конкретным HTTP статусом в контроллере.', 'Wersatil'),
    ('Пример использования ResponseStatusException?', 'throw new ResponseStatusException(HttpStatus.NOT_FOUND, "User not found");', 'Wersatil'),
    ('Как логировать исключения в @ControllerAdvice?', 'Использовать log.error("message", ex) внутри методов с @ExceptionHandler.', 'Wersatil'),
    ('Что такое error code в REST API?', 'Уникальный код ошибки для идентификации типа ошибки клиентом.', 'Wersatil'),
    ('Как разделять DTO для запроса и ответа?', 'Создать отдельные классы RequestDTO и ResponseDTO для разных целей.', 'Wersatil'),
    ('Что такое default error page в Spring Boot?', 'Страница /error, которая показывается при необработанных исключениях без кастомного контроллера.', 'Wersatil'),
    ('Как отключить default error page?', 'Создать кастомный @ControllerAdvice или свой /error endpoint.', 'Wersatil'),
    ('Что такое @ResponseStatus?', 'Аннотация для установки HTTP статуса при выбросе исключения.', 'Wersatil');