INSERT INTO question (question_text, answer, author) VALUES
    ('Что такое транзакция в Spring?', 'Блок кода, выполняемый как единое целое с поддержкой ACID, управляемый Spring контейнером.', 'Wersatil'),
    ('Что делает @Transactional?', 'Аннотация для объявления метода или класса как транзакционного.', 'Wersatil'),
    ('Где можно ставить @Transactional?', 'На методах сервиса или на уровне класса.', 'Wersatil'),
    ('Что такое propagation в транзакциях?', 'Поведение транзакции при вызове другого метода, который тоже транзакционный.', 'Wersatil'),
    ('Пример Propagation.REQUIRED?', 'Использует существующую транзакцию или создает новую, если нет.', 'Wersatil'),
    ('Пример Propagation.REQUIRES_NEW?', 'Всегда создает новую транзакцию, при этом существующая приостанавливается.', 'Wersatil'),
    ('Пример Propagation.NESTED?', 'Создает вложенную транзакцию с использованием savepoint, если есть существующая транзакция.', 'Wersatil'),
    ('Что делает Isolation?', 'Определяет уровень изоляции между параллельными транзакциями.', 'Wersatil'),
    ('Пример Isolation.READ_UNCOMMITTED?', 'Разрешает dirty read, транзакция видит незавершенные изменения других.', 'Wersatil'),
    ('Пример Isolation.READ_COMMITTED?', 'Запрещает dirty read, транзакция видит только подтвержденные данные.', 'Wersatil'),
    ('Пример Isolation.REPEATABLE_READ?', 'Запрещает dirty и non-repeatable read, но phantom read возможен.', 'Wersatil'),
    ('Пример Isolation.SERIALIZABLE?', 'Полная изоляция транзакций, предотвращает все аномалии, но снижает производительность.', 'Wersatil'),
    ('Что такое rollback в Spring?', 'Откат транзакции при ошибке или исключении.', 'Wersatil'),
    ('Когда транзакция автоматически откатывается?', 'По unchecked (Runtime) исключениям по умолчанию.', 'Wersatil'),
    ('Можно ли откатить транзакцию при checked исключении?', 'Да, через параметр rollbackFor в @Transactional.', 'Wersatil'),
    ('Пример rollbackFor?', '@Transactional(rollbackFor = Exception.class) — откат при checked исключениях.', 'Wersatil'),
    ('Что делает noRollbackFor?', '@Transactional(noRollbackFor = SomeException.class) — исключение не вызывает откат.', 'Wersatil'),
    ('Что происходит при вызове метода внутри того же класса с @Transactional?', 'Транзакция может не сработать из-за того, что Spring AOP прокси не перехватывает внутренние вызовы.', 'Wersatil'),
    ('Как решить проблему внутреннего вызова метода с @Transactional?', 'Вынести метод в отдельный бин или использовать self-injection через ApplicationContext.', 'Wersatil'),
    ('Что такое readOnly=true?', '@Transactional(readOnly=true) оптимизирует транзакцию для операций только чтения.', 'Wersatil'),
    ('Чем отличается programmatic и declarative транзакции?', 'Programmatic — управление через TransactionTemplate или EntityManager, declarative — через @Transactional.', 'Wersatil'),
    ('Что такое TransactionManager в Spring?', 'Интерфейс, управляющий транзакциями, например, PlatformTransactionManager.', 'Wersatil'),
    ('Примеры реализаций TransactionManager?', 'DataSourceTransactionManager, JpaTransactionManager, HibernateTransactionManager.', 'Wersatil'),
    ('Можно ли смешивать разные TransactionManager в проекте?', 'Да, но нужно явно указывать бин через @Transactional("transactionManagerName").', 'Wersatil'),
    ('Что такое savepoint?', 'Точка в транзакции, к которой можно откатиться без полного отката транзакции.', 'Wersatil'),
    ('Как Nested транзакции используют savepoint?', 'При Propagation.NESTED создается savepoint, rollback откатывает до него.', 'Wersatil'),
    ('Что такое commit?', 'Подтверждение всех изменений транзакции и их сохранение в базе.', 'Wersatil'),
    ('Что такое rollback-only?', 'Флаг, устанавливаемый вручную для отката транзакции без выброса исключения.', 'Wersatil'),
    ('Как вручную пометить транзакцию для отката?', 'TransactionAspectSupport.currentTransactionStatus().setRollbackOnly();', 'Wersatil'),
    ('Что такое ChainedTransactionManager?', 'Менеджер транзакций для работы с несколькими ресурсами одновременно.', 'Wersatil'),
    ('Можно ли управлять временем ожидания транзакции?', 'Да, через параметр timeout в @Transactional.', 'Wersatil'),
    ('Что делает timeout в @Transactional?', 'Если транзакция не завершена за указанный промежуток времени, она откатывается.', 'Wersatil'),
    ('Что такое nested transaction rollback?', 'Откат только вложенной транзакции до savepoint без отката родителя.', 'Wersatil'),
    ('Что такое propagation SUPPORTS?', 'Использует существующую транзакцию, если есть, иначе работает без транзакции.', 'Wersatil'),
    ('Что такое propagation MANDATORY?', 'Метод должен быть вызван внутри существующей транзакции, иначе выбрасывается исключение.', 'Wersatil'),
    ('Что такое propagation NEVER?', 'Метод не должен выполняться в транзакции, иначе выбрасывается исключение.', 'Wersatil'),
    ('Что такое propagation NOT_SUPPORTED?', 'Приостанавливает текущую транзакцию, метод выполняется без нее.', 'Wersatil'),
    ('Как @Transactional влияет на lazy загрузку?', 'Если метод завершился и сессия закрыта, доступ к ленивым коллекциям вызовет LazyInitializationException.', 'Wersatil'),
    ('Можно ли комбинировать readOnly и propagation?', 'Да, например @Transactional(readOnly=true, propagation=REQUIRED).', 'Wersatil'),
    ('Что такое rollback на конкретное исключение?', 'Транзакция откатывается только если выброшено указанное исключение.', 'Wersatil'),
    ('Что такое commit на конкретное исключение?', 'Можно предотвратить откат при указанном исключении через noRollbackFor.', 'Wersatil'),
    ('Почему declarative transactions предпочтительнее?', 'Меньше кода, легче поддерживать и интегрировать с AOP.', 'Wersatil'),
    ('Что происходит при исключении внутри nested транзакции?', 'Только вложенная транзакция откатывается до savepoint, родительская продолжается.', 'Wersatil'),
    ('Как @Transactional работает с proxy?', 'Spring создает прокси, который перехватывает вызовы методов и управляет транзакцией.', 'Wersatil'),
    ('Что делает rollbackForClassName?', 'Позволяет указать имя класса исключения для отката транзакции.', 'Wersatil'),
    ('Можно ли @Transactional на интерфейсе?', 'Да, если используется JDK dynamic proxy, но лучше на классе.', 'Wersatil'),
    ('Можно ли комбинировать @Transactional и async?', 'Да, но нужно понимать, что @Async выполняется в другом потоке, транзакции не разделяются автоматически.', 'Wersatil'),
    ('Как проверить, находится ли транзакция в процессе?', 'TransactionSynchronizationManager.isActualTransactionActive()', 'Wersatil'),
    ('Что такое global rollback?', 'Откат всей транзакции вместе со всеми nested и внутренними вызовами.', 'Wersatil'),
    ('Что такое local rollback?', 'Откат только части транзакции, например через savepoint в nested транзакции.', 'Wersatil');