INSERT INTO question (question_text, answer, author) VALUES
    ('Что такое Layered Architecture?', 'Архитектура приложения, разделяющая код на слои: Controller, Service, Repository.', 'Wersatil'),
    ('Зачем нужна слоистая архитектура?', 'Для разделения ответственности, улучшения тестируемости и поддержки кода.', 'Wersatil'),
--    ('Что такое MapStruct?', 'Фреймворк для автоматического маппинга между DTO и Entity.', 'Wersatil'),
    ('Чем MapStruct лучше ручного маппинга?', '1.Генерирует код на этапе компиляции. 2.Уменьшает количество ошибок. 3.Повышает производительность.', 'Wersatil'),
    ('Что делает @Mapping в MapStruct?', 'Позволяет настроить сопоставление полей с разными именами.', 'Wersatil'),
    ('Что такое @ControllerAdvice?', 'Аннотация для глобальной обработки исключений в Spring MVC.', 'Wersatil'),
    ('Что такое Saga?', 'аттерн управления распределёнными транзакциями в микросервисной архитектуре, когда нет одной общей ACID-транзакции, но нужна согласованность данных.', 'Wersatil'),
    ('Что делает @ExceptionHandler?', 'Обрабатывает конкретный тип исключения и формирует ответ клиенту.', 'Wersatil'),
    ('Как вернуть кастомный error response?', 'Создать DTO для ошибки и вернуть через ResponseEntity с нужным статусом.', 'Wersatil'),
    ('Какие уровни логирования бывают и какие в каких слкчаях надо использовать?', 'TRACE, DEBUG, INFO, WARN, ERROR.', 'Wersatil'),
    ('Что такое REST error handling?', 'Обработка ошибок в REST API с возвращением структурированного ответа клиенту.', 'Wersatil'),
    ('Что такое ApiError DTO?', 'DTO, который используется для унифицированного описания ошибки API и возвращается клиенту вместо stack trace или внутренних исключений..', 'Wersatil'),
    ('Что такое BindingResult?', 'Объект для проверки ошибок валидации при использовании @Valid в контроллере.', 'Wersatil'),
    ('Как настроить возвращение разных HTTP статусов для разных исключений?', 'Через @ExceptionHandler для каждого типа исключения и ResponseEntity с нужным статусом.', 'Wersatil'),
    ('Что такое Validation DTO?', 'DTO с аннотациями валидации (@NotNull, @Size, @Email) для проверки данных входящих запросов.', 'Wersatil'),
    ('Как использовать @Valid?', 'Проставить @Valid перед DTO в контроллере для активации валидации.', 'Wersatil'),
    ('Что такое nested exception handling?', 'Обработка исключений, которые вложены друг в друга (cause), например при PersistenceException.', 'Wersatil'),
    ('Что такое ErrorAttributes?', 'Интерфейс Spring Boot для формирования структуры ответа при ошибке.', 'Wersatil'),
    ('Что такое DefaultErrorAttributes?', 'Стандартная реализация Spring Boot для создания error response в error.', 'Wersatil'),
    ('Как добавить кастомные поля в error response?', 'Создать свой класс, реализующий ErrorAttributes и переопределить getErrorAttributes().', 'Wersatil'),
    ('Что такое centralized logging?', 'Сбор логов с разных компонентов приложения в одном месте для анализа.', 'Wersatil'),
    ('Что такое MDC в логировании?', 'MDC (Mapped Diagnostic Context) — это механизм логирования, который позволяет добавлять контекстные данные в логи автоматически, без передачи их в каждый вызов логгера. Например userId в каждый лог: MDC.put("userId", id);', 'Wersatil'),
    ('Что такое structured logging?', 'Логирование в формате JSON или с ключами для удобного анализа в ELK или Grafana.', 'Wersatil'),
    ('Что такое logging pattern?', 'Формат записи лога, например: %d{HH:mm:ss} %-5level %logger{36} - %msg%n', 'Wersatil'),
    ('Что делает @Mapper(componentModel = "spring")?', 'Указывает MapStruct на то, что создавать бин Spring для внедрения через @Autowired.', 'Wersatil'),
    ('Чем MapStruct отличается от ModelMapper?', 'MapStruct генерирует код на этапе компиляции, благодаря этому быстрее и безопаснее работает и ошибки ловит уже на этапе компиляции (до начала работы). ModelMapper делает маппинг во время выполнения.', 'Wersatil'),
    ('Как обрабатывать ValidationException глобально?', 'Создать @ExceptionHandler(ValidationException.class) в @ControllerAdvice и вернуть ResponseEntity с ошибкой.', 'Wersatil'),
    ('Что такое ResponseStatusException?', 'Класс для выброса исключения с конкретным HTTP статусом в контроллере.', 'Wersatil'),
    ('Что такое error code в REST API?', 'Уникальный код ошибки для идентификации типа ошибки клиентом.', 'Wersatil'),
    ('Что такое default error page в Spring Boot?', 'Страница /error, которая показывается при необработанных исключениях без кастомного контроллера.', 'Wersatil'),
    ('Как отключить default error page?', 'Создать кастомный @ControllerAdvice или свой /error endpoint.', 'Wersatil'),
    ('Что такое @ResponseStatus?', 'Аннотация для установки HTTP статуса при выбросе исключения.', 'Wersatil');